# Generated by Django 2.2.16 on 2020-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0003_reply_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
